# Start from the latest golang base image
FROM golang:1.19.2

LABEL author="Mauricio Milano"
LABEL description="dex challenge"
LABEL version="1.0"


WORKDIR /app/go_app
# COPY go.mod ./go.mod
COPY go.sum go.sum ./ 

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

ENV APP_POSTGRES_HOST='postgres'
ENV APP_POSTGRES_PORT='5432'
ENV APP_POSTGRES_DB='store'
ENV APP_POSTGRES_USER='app'
ENV APP_POSTGRES_PASS='APP'
ENV APP_PORT=":3000"

RUN go mod download

EXPOSE 3000

CMD ["go","run","main.go"]
